# -*- mode: ruby -*-
# vi: set ft=ruby :
required_plugins = %w( vagrant-notify-forwarder vagrant-hostmanager)
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

$script = <<SCRIPT
wget "https://download.docker.com/linux/ubuntu/dists/trusty/pool/stable/amd64/docker-ce_17.03.1~ce-0~ubuntu-trusty_amd64.deb"
apt-get install libsystemd-journal0
dpkg -i docker-ce_17.03.1~ce-0~ubuntu-trusty_amd64.deb
groupadd docker
usermod -aG docker $USER
SCRIPT

Vagrant.configure("2") do |config|

	if !defined?(proxy_url) || proxy_url.nil? || proxy_url.empty?

		# No proxy setup necessary.

	else
		# Setup proxies

		ENV['http_proxy']  = proxy_url
		ENV['https_proxy'] = proxy_url
	end

	config.vm.define "host"
	
	# config.vm.network "private_network", ip: "192.168.50.50"
	config.vm.box = "williamyeh/ubuntu-trusty64-docker"
	# config.vm.box = "lookfwd/scrapybook"



	# Setting up ports
	(
		[27017] +  					 #MongoDB
		[2222] +					#dev
		[9200] +                      # ES
		[6379] +                      # Redis
		[3306] +                      # MySQL
		[9312] +                      # Web
	[]).each do |port|
		config.vm.network "forwarded_port", guest: port, host: port, host_ip: "localhost", auto_correct: true
	end
	config.notify_forwarder.port = 22020


	# Set the mem/cpu requirements
	config.vm.provider :virtualbox do |vb|
		vb.memory = 2048
		vb.cpus = 4
		vb.name = "host"
		vb.check_guest_additions = false
	end

	config.notify_forwarder.port = 22020

#   config.hostmanager.enabled = true
#   config.hostmanager.manage_guest = true
#   config.vm.provision :hostmanager

#   config.vm.provision :ansible do |ansible|
#     ansible.playbook      = "../ansible/playbook.yml"
#     ansible.sudo          = true
#   end

end
