# Set if you are behind proxy

required_plugins = %w( vagrant-hostmanager vagrant-notify-forwarder )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

#proxy_url = "http://user:pass@proxy.com:8080/"

Vagrant.configure("2") do |config|

	if !defined?(proxy_url) || proxy_url.nil? || proxy_url.empty?

		# No proxy setup necessary.

	else
		# Setup proxies

		ENV['http_proxy']  = proxy_url
		ENV['https_proxy'] = proxy_url
	end
	
	config.ssh.insert_key = false

	config.vm.define "host"
	config.vm.hostname = "host"
	config.vm.box = "williamyeh/ubuntu-trusty64-docker"

	# Setting up ports
	(
		[29324] +
		[9200] +                      # ES
		[6379] +                      # Redis
		[3306] +                      # MySQL
		[9312] +                      # Web
		(6800..6803).to_a +           # Scrapyd
		[21] + (30000..30009).to_a  + # Spark
	[]).each do |port|
		config.vm.network "forwarded_port", guest: port, host: port, host_ip: "localhost", auto_correct: true
	end


	# Set the mem/cpu requirements
	config.vm.provider :virtualbox do |vb|
		vb.memory = 2048
		vb.cpus = 4
		vb.name = "docker-provider"
		vb.check_guest_additions = false
	end

#   config.hostmanager.enabled = true
#   config.hostmanager.manage_guest = true
#   config.vm.provision :hostmanager

#   config.vm.provision :ansible do |ansible|
#     ansible.playbook      = "ansible/playbook.yml"
#     ansible.sudo          = true
#   end
end
