- name: Setup scrapy environment
  hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - python-dev 
        - python-pip 
        - libxml2-dev 
        - libxslt1-dev 
        - zlib1g-dev 
        - libffi-dev 
        - libssl-dev
